[params]
  paginate = 5
  copyrightYears = "MMXXV"
  enableBlogPost = true
  enableTOC = true
  favicon_svg = "/images/cm.svg"
  contacts = ['<h4 class="contact-link">Mail</h4><a href="mailto:mail@christianmahnke.de" title="E-Mail senden">mail@christianmahnke.de</a>']
  disableScale = true
  description = "Das nicht gebaute Göttingen"
  subTitle = "Das nicht gebaute Göttingen"
  debug = true

[params.author]
    email = 'mail@christianmahnke.de'
    name = 'Christian Mahnke'

[params.preview]
    outputPrefix = "ogPreview"
    outputSuffix = ".png"
    format =  "svg"
    image = "front.png"
    source = "post"
    [params.preview.size]
        height = 630
        width = 1200
    [params.preview.svg]
        template = "./Source Files/Other/preview-template.svg"
        scale = "width"
        removeMissing = true
